### ISSUE TITLE
EXCUSE ME

### ISSUE THREAD

**Issue by thetakodev** [kukiteam/kukipack#7]
Refined Storage was never meant to be a part of the modpack, as it destroys the fun of having storage and complex factories (automation and etc)
U rtard, im deleting it now

**Comment by Sascha-T** [comment]
i see what you mean but

**Comment by Sascha-T** [comment]
everyone likes it.

**Comment by thetakodev** [comment]
But no

**Comment by thetakodev** [comment]
It break balance

**Comment by thetakodev** [comment]
We already have Iron Chests

**Comment by thetakodev** [comment]
It already tips the scales quite a bit

**Comment by Sascha-T** [comment]
do not remove the mod now

**Comment by Sascha-T** [comment]
or i will refund everyone with 64 of whatever they CLAIM to have lost (with no checking)

**Comment by Sascha-T** [comment]
we also held a vote on it. majority ruled yes.

**Comment by thetakodev** [comment]
ok fuck it, im just gonna fucking leave the server alone, gonna go instead work on Kukicraft

**Comment by Sascha-T** [comment]
good idea. we want the proper modpack

**Comment by thetakodev** [comment]
~~nuke it with useless mods~~

**Comment by Sascha-T** [comment]
(and ban that one dude that raided all discord servers)

**Comment by thetakodev** [comment]
wait who?

**Comment by thetakodev** [comment]
don't u have perms?

**Comment by thetakodev** [comment]
also is it Romelo?

**Comment by Sascha-T** [comment]
I only have perms on KukiPack

**Comment by Sascha-T** [comment]
and its <@503031334835322891>

**Comment by Sascha-T** [comment]
![grafik](https://user-images.githubusercontent.com/16324266/47753947-9607ca00-dc99-11e8-873c-bf6f5728fbad.png)

**Comment by thetakodev** [comment]
nice, i don't even know who the fuc it is

**Comment by thetakodev** [comment]
ah

**Comment by thetakodev** [comment]
i will ban him... 6th of november

**Comment by Sascha-T** [comment]
do you know who that is?

**Comment by thetakodev** [comment]
idk, but i saw him

**Comment by thetakodev** [comment]
~~this is nice replacement to discord~~

**Comment by Sascha-T** [comment]
anyway dont BORK the modpack, democracy decided we are adding REFINEDSTORAGE

**Comment by thetakodev** [comment]
ok

**Comment by thetakodev** [comment]
~~delets the fucking repo~~

**Comment by Sascha-T** [comment]
![grafik](https://user-images.githubusercontent.com/16324266/47754094-13333f00-dc9a-11e8-8db7-222db8d42a49.png)

**Comment by thetakodev** [comment]
oof

**Comment by thetakodev** [comment]
this is still an issue :^)

**Comment by thetakodev** [comment]
its unresolved

**Comment by thetakodev** [comment]
**THE MODPACK IS UNBALANCE**

**Comment by thetakodev** [comment]
![image](https://user-images.githubusercontent.com/32229391/47754223-3ca89680-dcab-11e8-8bd7-aa0c94be9fa2.png)
check this out

**Comment by Sascha-T** [comment]
you know what

**Comment by thetakodev** [comment]
wait what the fuc its the wrong pic, fuck apple, and mac, and this laptop in general, i copied that pic 5 min's ago, and it did't paste anything

**Comment by Sascha-T** [comment]
![grafik](https://user-images.githubusercontent.com/16324266/47754277-ad938280-dc9a-11e8-9f92-2feab176324f.png)
cya dude

**Comment by thetakodev** [comment]
nice
![image](https://user-images.githubusercontent.com/32229391/47754313-898c6d00-dcab-11e8-9f3e-819782ed4c44.png)

**Comment by Sascha-T** [comment]
![grafik](https://user-images.githubusercontent.com/16324266/47754404-0d8a2900-dc9b-11e8-8a92-6e35ee0406ce.png)
frick off

**Comment by thetakodev** [comment]
this is fun

**Comment by thetakodev** [comment]
i love how it says "heute um" and i misread it as "hate 'em"

**Comment by Sascha-T** [comment]
sotp

**Comment by thetakodev** [comment]
this is a big issue

**Comment by Sascha-T** [comment]
sathape or i make you stop

**Comment by thetakodev** [comment]
it grow fast

**Comment by thetakodev** [comment]
wait

**Comment by thetakodev** [comment]
this is still a big issue

**Comment by thetakodev** [comment]
oof

**Comment by thetakodev** [comment]
we need help

**Comment by thetakodev** [comment]
oof

**Comment by Sascha-T** [comment]
i know who can fix this

**Comment by thetakodev** [comment]
this is correct now

**Comment by Sascha-T** [comment]
there now let  @kukiteam-jenkins work

**Comment by thetakodev** [comment]
this is even better

**Comment by Sascha-T** [comment]
high iq

**Comment by thetakodev** [comment]
moar labels

**Comment by thetakodev** [comment]
why tho

**Comment by Sascha-T** [comment]
blame it on alerod

**Comment by thetakodev** [comment]
gtg

**Comment by Sascha-T** [comment]
wait ofr a minut

**Comment by Sascha-T** [comment]
are you still there? im gonna push the fix now

**Comment by Sascha-T** [comment]
hello?

**Comment by Sascha-T** [comment]
damn, this repo lives for another day i guess :f

**Comment by Solly-W** [comment]
Nobody likes looking through a hundred chests to find items. It takes up the majority of my time when I could be doing far more fun and useful things, and gives me headaches, as well as just being boring and frustrating. Refined storage was added to centralise storage, not for the automation. Immersive engineering and quark oddities should still be used for that.

**Comment by Solly-W** [comment]
And since there is no way to automatically input items into the network, well still are chests and drawers and silos everywhere to store the automated materials or materials we have large amounts of

**Comment by Solly-W** [comment]
And for the love of god do not abandon this pack tako, sascha's great but we still need your common sense to oversee everything ~~No offence to you, sascha~~

**Comment by Sascha-T** [comment]
Tako: being idot
Me: also idot
Solly: **writes a 69 page long essay on how the democratic decision to add the mod was good and adds intellectual reasons**

**Comment by thetakodev** [comment]
this was worth it
<img width="968" alt="2018-11-01 10 18 07" src="https://user-images.githubusercontent.com/32229391/47838178-9f8b5200-ddbf-11e8-9255-d4f3b220a47d.png">

**Comment by thetakodev** [comment]
Needs more spam

**Comment by Ale32bit** [comment]
u wot

**Comment by cyb3rm4n** [comment]
@thetakodev check out discord plz, if u r in moscow, write me back

**Comment by Solly-W** [comment]
Hey people, GitHub issue comments != social media!

**Comment by Solly-W** [comment]
Hey people, GitHub issue comments != social media!

**Comment by Solly-W** [comment]
Why the hecc did that just post twice

**Comment by Ale32bit** [comment]
This is a big issue

**Comment by Solly-W** [comment]
🤦‍♂️

**Comment by Ale32bit** [comment]
god is dead and we killed him

**Comment by Solly-W** [comment]
🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️

**Comment by Ale32bit** [comment]
![hmm](https://i.ale32bit.me/zIjfi.png)

**Comment by Solly-W** [comment]
IK discord sucks at reading combo emoji characters

**Comment by Sascha-T** [comment]
wait...
